# Generated by Django 4.2.7 on 2025-08-05 06:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['name'], 'verbose_name': 'Service Area', 'verbose_name_plural': 'Service Areas'},
        ),
        migrations.AlterModelOptions(
            name='trustbadge',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Trust Badge', 'verbose_name_plural': 'Trust Badges'},
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='slug',
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='review_url',
            field=models.URLField(blank=True, help_text='Link to original review'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='city',
            field=models.CharField(db_index=True, default='Toronto', max_length=100),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='province',
            field=models.CharField(default='Ontario', max_length=50),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='url',
            field=models.URLField(blank=True, help_text='Link to certification or badge'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='platform',
            field=models.CharField(choices=[('google', 'Google'), ('yelp', 'Yelp'), ('trustpilot', 'Trustpilot'), ('reddit', 'Reddit')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='areas.servicearea'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Google Maps embed code'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CA'),
        ),
        migrations.AlterField(
            model_name='trustbadge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
