# Generated by Django 4.2.7 on 2025-08-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_review_options_alter_servicearea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='google_business_url',
            field=models.URLField(blank=True, help_text='Google Business Profile URL for reviews'),
        ),
    ]
