# Generated by Django 4.2.7 on 2025-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_servicearea_google_business_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='reddit_url',
            field=models.URLField(blank=True, help_text='Reddit discussion or business page URL'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='trustpilot_url',
            field=models.URLField(blank=True, help_text='Trustpilot business page URL'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='yelp_url',
            field=models.URLField(blank=True, help_text='Yelp business page URL'),
        ),
    ]
