# Generated by Django 4.2.7 on 2025-08-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking', 'New Booking'), ('contact', 'New Contact Message'), ('quote', 'New Quote Request')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_id', models.PositiveIntegerField(help_text='ID of the related booking/contact/quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
