# Generated by Django 4.2.7 on 2025-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_faq_alter_service_options_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='Link to Google review'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified customer review'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
