# Generated by Django 4.2.7 on 2025-08-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_testimonial_google_review_url_and_more'),
        ('areas', '0002_alter_review_options_alter_servicearea_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Brief description for SEO', max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('diy', 'DIY Tips'), ('maintenance', 'Maintenance Guides'), ('seasonal', 'Seasonal Advice'), ('case_study', 'Case Studies'), ('news', 'News & Updates')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=160)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.servicearea')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
