# Generated by Django 4.2.7 on 2025-08-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_faq_alter_service_options_alter_testimonial_options_and_more'),
        ('areas', '0002_alter_review_options_alter_servicearea_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('before_after', 'Before & After'), ('emergency', 'Emergency Repairs'), ('installation', 'Installations'), ('maintenance', 'Maintenance'), ('tools', 'Tools & Equipment'), ('team', 'Our Team')], default='installation', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text='Location where work was done (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='areas.servicearea')),
                ('service', models.ForeignKey(blank=True, help_text='Related service (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='services.service')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
