# Generated by Django 4.2.7 on 2025-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='after_image',
            field=models.ImageField(blank=True, help_text='After image for before/after comparisons', null=True, upload_to='gallery/after/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Before image for before/after comparisons', null=True, upload_to='gallery/before/'),
        ),
    ]
