# Generated by Django 4.2.7 on 2025-08-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_servicearea_reddit_url_servicearea_trustpilot_url_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='service_area',
            field=models.ForeignKey(blank=True, help_text="Customer's service location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='areas.servicearea'),
        ),
    ]
