# Generated by Django 4.2.7 on 2025-08-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_testimonial_google_review_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('labor_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('selected_options', models.JSONField(default=list)),
                ('estimated_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price_modifier', models.DecimalField(decimal_places=2, help_text='Additional cost', max_digits=6)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quotes.quotecalculator')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
